name: Sync Rules

on:
  push:
    branches:
      - main
      - master
      - Surge
    paths:
      - "**"
  workflow_dispatch:

concurrency:
  group: surge-format-${{ github.ref }}
  cancel-in-progress: true

jobs:
  sync:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}
          fetch-depth: 2

      - name: Check commit message
        id: check_commit
        run: |
          COMMIT_MSG=$(git log -1 --pretty=%B)
          if [[ $COMMIT_MSG == *"[AUTO_SYNC]"* || $COMMIT_MSG == *"[AUTO_FORMAT]"* ]]; then
            echo "Skipping workflow as this is an automated sync commit"
            echo "skip=true" >> "$GITHUB_OUTPUT"
          else
            echo "Proceeding with sync"
            echo "skip=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Set up Python
        if: steps.check_commit.outputs.skip == 'false'
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Configure Git
        if: steps.check_commit.outputs.skip == 'false'
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"

      - name: Run format script
        if: steps.check_commit.outputs.skip == 'false'
        run: python format_rules.py
